### ISSUE TITLE
Pipeline always chooses minisam assemblies?

### ISSUE THREAD

**Issue by fkollingiv** [mckennalab/Circuitseq#14]
When processing multiple samples through the pipeline, many fail to produce a final fasta assembly. Looking back through the intermediate files, the ones that fail appear to produce Flye assemblies but have empty miniasm .gfa outputs. It appears that the pipeline does not select the Flye assembly for further processing and these samples do not move through the subsequent steps. This can be seen below, where Flye produces 35 assemblies (all files contain a contig), Miniasm produces 34 .gfa files (but several are empty), and only 28 samples make it to the "ConvertGraph" and subsequent steps.

[49/c76210] process > FilterReads (34)            [100%] 34 of 34, cached: 34 ✔
[65/062d34] process > CanuCorrect (34)            [100%] 34 of 34, cached: 34 ✔
[03/85a5f8] process > Flye (5)                    [100%] 35 of 35, cached: 33, failed: 2, retries: 1 ✔
[83/bc74c5] process > Miniasm (34)                [100%] 34 of 34, cached: 34 ✔
[4d/348ecb] process > ConvertGraph (28)           [100%] 28 of 28, cached: 28 ✔
[79/f5699b] process > AssessAssemblyApproach (27) [100%] 27 of 27, cached: 27 ✔
[9c/716948] process > MedakaConsensus (27)        [100%] 27 of 27, cached: 27 ✔

Is there a way to ensure the Flye assemblies are selected in this scenario?

**Comment by aaronmck** [comment]
I believe this is related to issue #13, fixing it now

**Comment by aaronmck** [comment]
I think this is be fixed in the current version. I'm running full testing right now, but if you wanted to update, you'll need to pull the new docker/singularity image from the main page (the location changed a little). It certainly picks the better build by the simple rules now, but I just want to make sure nothing downstream is affected.

**Comment by fkollingiv** [comment]
Thank you Aaron!

Just to confirm, the new singularity location is the one shown on the
githib page?

docker://aaronmck/plasmidassembly:1_0_1

Fred

**Comment by fkollingiv** [comment]
I cleaned out the old plasmidassembly.sif file, built the new 1_0_1 docker image and re-cloned the git repository. When I run the updated pipeline on my dataset, or the test data I am seeing the following:

[-        ] process > GuppyBaseCalling            -
[-        ] process > GuppyDemultiplex            -
[09/d35818] process > GuppyDemultiplexExisting    [100%] 1 of 1 ✔
[-        ] process > pycoQC                      -
[-        ] process > AlignReadsPre               -
[ce/fd6a50] process > Porechop (1)                [100%] 1 of 1 ✔
[-        ] process > AlignReadsPostLengthFilter  -
[d4/afcf2f] process > FilterReads (1)             [100%] 1 of 1 ✔
[-        ] process > CanuCorrect                 -
[-        ] process > Flye                        -
[-        ] process > Miniasm                     -
[-        ] process > ConvertGraph                -
[-        ] process > AssessAssemblyApproach      -
[-        ] process > MedakaConsensus             -
[-        ] process > LCPCorrectionFlye           -
[-        ] process > Rotate                      -
[-        ] process > MedakaConsensusLCP          -
[-        ] process > MedakaPolish                -
[-        ] process > MedakaPolish2               -
[-        ] process > Fast5Subset                 -
[-        ] process > OGMethylationCalling        -
[-        ] process > ReferenceCopy               -
[-        ] process > AlignReads                  -
[-        ] process > AlignReadsNanofilter        -
[-        ] process > AssessContamination         -
[8c/b3d836] process > ContaminationAggregation    [100%] 1 of 1 ✔
[-        ] process > PlasmidComparison           -
[e7/76aca4] process > PlasmidComparisonCollection [100%] 1 of 1 ✔

The pipeline appears to be skipping all of the assembly and polishing steps and skipping to the final few steps of the pipeline.

**Comment by aaronmck** [comment]
Weird; I just did a full clean and rerun and didn't have the issue (I got 27 final plasmids). Is this in a fresh install, removing the work and results directories? I can also take a look if you have a path

**Comment by aaronmck** [comment]
there was another issue, the nanofilter within the docker contain was broken by some python dependency changes (I must have kept that cached...not sure why it worked). I've redone the docker container that's listed on the main page, so pulling that again should fix it. I'm checking on the nanopore machine now here: ~/Plasmid-seq_Runs/221122/aarons_run_2022_11_24

**Comment by aaronmck** [comment]
I've also added some better checks around the assembly assessments. Let me know how it works for you.

**Comment by aaronmck** [comment]
here's the output dir: ~/Plasmid-seq_Runs/221122/aarons_run_2022_11_24

**Comment by fkollingiv** [comment]
Pipeline is running well with the expected behavior. Thanks for the quick
fix Aaron!
