### ISSUE TITLE
Does Circuitseq expect multiplexed fast[5q]s?

### ISSUE THREAD

**Issue by pdexheimer** [mckennalab/Circuitseq#17]
Hi -

I'm struggling to get Circuitseq running on my data. I've successfully run it on the example data, but when I try to run on my own data I get the same behavior as reported in #12 - Nextflow runs for about 30 seconds, returns no error code, but the progress report shows that GuppyDemultiplexExisting failed and then only ContaminationAggregation and PlasmidComparisonCollection were run on no data.  I can't any output from GuppyDemultiplexExisting to diagnose why it failed.

However... my data are already demultiplexed. Inside the fastq_pass directory, I have subdirectories for barcode01-barcode11, plus an unclassified subdirectory, each one containing somewhere between 1 and 15 separate fastqs. Is there a way to bypass both basecalling and demultiplexing in CircuitSeq, or do I need to try and get a single massive multiplexed fastq (or fast5) from the instrument?

**Comment by aaronmck** [comment]
Hi @ pdexheimer,

It should work, as long as that has the standard demultiplexing file layout (it looks for files with the pattern saved_data/barcode**/**.fastq.gz and saved_data/barcoding_summary.txt).  Could you send the nexflow log? Sorry this part is a bit brittle, it can be tricky to make sure everyone's pre-called samples line up right, we'll add some more documentation about this step too.

-Aaron

**Comment by aaronmck** [comment]
didn't mean to close, reopening...

**Comment by femiliani** [comment]
hey @pdexheimer turns out that our guppy_barcoder step actually just uses un-demultiplexed fastqs. and since it wasnt set to look for them recursively it wasnt seeing yours. i changed the pipeline file to include the recursive option so it will look for them all. 

One caveat is, what did you barcode your plasmids with? if you arent using ours or the nanopore official ones you will need to mount your barcoding config files into the container. `--bind /source/directory:/location/in/container` and then you would use the `/location/in/container` instead of our path for this parameter `--barcodes /plasmidseq/barcodes/v2/`

**Comment by pdexheimer** [comment]
Thanks to both of you! @femiliani - unfortunately the change you made was not enough. Rerunning (after a `git pull`) had the same results.

Just so that everything is all in one place, here is my run_nf.sh (I used fake env vars here for legibility, all paths are absolute):

```
NXF_VER=21.10.6 nextflow run $Circuitseq/pipelines/CircuitSeq.nf \
           --GPU ON \
           -c $Circuitseq/pipelines/nextflow.config \
           -with-singularity $Circuitseq/plasmidassembly.sif \
           --samplesheet $ONT_RUN/samplesheet.txt \
           --use_existing_basecalls true \
           --fast5 "none" \
           --basecalling_dir $ONT_RUN/fastq_pass \
           --base_calling_summary_file $ONT_RUN/sequencing_summary_ALM456_190e2f16.txt \
           --barcodes $Circuitseq/barcodes/nanopore_official/ \
           --barcode_kit SQK-RBK004 \
           --guppy_model dna_r9.4.1_450bps_hac_model.cfg \
           --medaka_model r941_min_sup_g507 \
           --gpu_slot cuda:0 \
           --barcode_min_score 65 \
           --quality_control_processes true \
           -resume
```

Here are the first couple rows of `samplesheet.txt` (I have 8 samples in total, though I just noticed that I have 11 barcodes in the fastq directory.  I'll ask about that):

```
position	sample	reference
01	AE1	NA
02	AE2	NA
```

Here are the first couple rows of the sequencing summary file:

```
filename_fastq	filename_fast5	parent_read_id	read_id	run_id	channel	mux	start_time	duration	num_events	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template	pore_type	experiment_id	sample_id	end_reason	alias	type	barcode_arrangement	barcode_full_arrangement	barcode_kit	barcode_variant	barcode_score	barcode_front_id	barcode_front_score	barcode_front_refseq	barcode_front_foundseq	barcode_front_foundseq_length	barcode_front_begin_index	barcode_rear_id	barcode_rear_score	barcode_rear_refseq	barcode_rear_foundseq	barcode_rear_foundseq_length	barcode_rear_end_index
ALM456_fail_unclassified_190e2f16_0.fastq.gz	ALM456_fail_unclassified_190e2f16_0.fast5	58d1c801-7258-4ae9-8ead-0a328e0608fc	58d1c801-7258-4ae9-8ead-0a328e0608fc	190e2f165ccc0f49a2df3d526c22415fb6d2839b	109	1	43.434250	0.842750	674FALSE	43.573000	563	0.704000	237	6.639208	2.654663	85.427872	9.877056	not_set	Plasmid_Trial_20221228	PlasmidPool_20221228	signal_positive	unclassified	na	unclassified	RBK401	RBK4	n/a	38.000000	RBK01_FWD	38.000000	GCTTGGGTGTTTAACCAAGAAAGTTGTCGGTGTCTTTGTGGTTTTCGCATTTATCGTGAAACGCTTTCGCGTTTTTCGTGCGCCGCTTCA	GATTGTTTTAACCTTTAAAAAACGTCGTTTTGGGGCTTTATCGTGAAACGCTTTCGCGACGCTTCACGGCGTCTGTTC	78	24	-	-inf	-	-	0	151
ALM456_pass_barcode05_190e2f16_0.fastq.gz	ALM456_pass_barcode05_190e2f16_0.fast5	fda9e76b-df0f-40ff-8c5e-a0752030409e	fda9e76b-df0f-40ff-8c5e-a0752030409e	190e2f165ccc0f49a2df3d526c22415fb6d2839b	42	1	42.943000	2.519500	2015	TRU42.943000	2015	2.519500	997	9.657346	3.000695	82.135521	10.223619	not_set	Plasmid_Trial_20221228	PlasmidPool_20221228	signal_positive	barcode05	test_sample	barcode05	RBK405	RBK4	n/a	99.000000	RBK05_FWD	99.000000	GCTTGGGTGTTTAACCCTTGTCCAGGGTTTGTGTAACCTTGTTTTCGCATTTATCGTGAAACGCTTTCGCGTTTTTCGTGCGCCGCTTCA	GTGGGTGTTTAACCCTTGTCCAGGGTTTGTGTAACCTTGTTTTCGCATTTATCGTGAAACGCTTTCGCGTTTTTCGTGCGCCGCTCA	87	59	-	-inf	-	-	0	151
```

In terms of figuring out how to set up Circuitseq, this file has caused me the most problems. The columns are not _exactly_ the same as the [example file](https://github.com/mckennalab/Circuitseq/blob/main/example_data/fastq/sequencing_summary.txt), but this the only tsv I can find in my data that's remotely close.  The fact that this file has one line per read (not fastq) threw me, but it looks like that's true of the example file as well.

For completeness, here's my [nextflow.log](https://github.com/mckennalab/Circuitseq/files/10460057/nextflow.log), and my results directory looks like this (numbers in brackets are the size in bytes, symbolic link destinations removed):

```
results/
├── [  39]  aggregate_assembly_assessment
│   └── [ 126]  all_nextpolish2.stats 
└── [  45]  aggregate_contamination
    └── [ 132]  all_contamination_stats.txt 

2 directories, 2 files
```

**Comment by femiliani** [comment]
Ah! i think we might have caught the culprit. Does this path lead to your machine? `--barcodes $Circuitseq/barcodes/nanopore_official/`. We have those barcode files in the repo for building the docker container, but to use the correct barcodes you have to use the ones in the container already (or mount that dir into the container). So the correct path for that should be `--barcodes /plasmidseq/barcodes/nanopore_official/`
I'll make sure the readme does a better job explaining that. 

As for the summary file... we can thank ONT for that, they keep updating it. To the point that if you use dorado it doesnt even produce one anymore. which is very annoying given there are some tools (like pycoQC) that require it. But that shouldn't be the problem in this case. 

Finally, the results directory looks normal for a failed run. it produces those directories first and slowly populates as the assemblies are made. the first time it will run without error it should start producing all the other directories too.

**Comment by femiliani** [comment]
I'm sorry this trouble shooting is being so difficult. Two things one is that we have the nanopore barcoding kits in the docker container you can set them with `--barcodes /plasmidseq/barcodes/nanopore_official/` and (i fully appreciate how wishy washy this sounds) it's possible you need to put the barcoding kit in quotes. 

Otherwise could you possibly send me a single fastq either through email (francesco.e.emiliani.gr[at]dartmouth.edu) or whatever way you feel comfortable with? And I'll try to run it on our end to troubleshoot.

**Comment by pdexheimer** [comment]
Success!

Thanks for all your help, @femiliani - Updating the barcode path (and quoting the kit for good measure) solved my problem. I see that the readme does include the correct path, so I guess chalk this up to user error. If I could make a couple of suggestions, though... I think it would help if you explicitly mention that the path is local to the container. I suspect that I saw the path, assumed that it was on your laptop or otherwise outdated, and pointed it to the barcodes directory that I knew existed. Alternatively, it might be helpful to give the `--barcodes` parameter just the name of the subdirectory within the barcodes dir - so it would look like `--barcode nanopore_official`, and then you could give it the proper path when invoking guppy. That would make it more complicated for users with custom barcodes, so it might or might not be worth it.

Thanks again for your help, and thanks for putting together this great tool!
