### ISSUE TITLE
Run Circuitseq without reference sequence

### ISSUE THREAD

**Issue by mcrone** [mckennalab/Circuitseq#3]
Firstly thank you for the cool tool! I'm just trying to get it to run and struggling a little.

With regards to the reference field in the samplesheet. How do I not specify this? I've tried NA, but it still tries to grep a file with NA. It also doesn't work if I just leave the field out. Even when using references from the epi2me pipeline it seems to just crash out after this step and not perform any of the assembly.

**Comment by aaronmck** [comment]
Hi mcrone,

Thanks for trying this out! We let some reference dependencies creep in our push to get this out. I've removed those dependencies and tested it with and without references. Also worth noting I've moved this into a single pipeline file [CircuitSeq.nf](https://github.com/mckennalab/Circuitseq/blob/main/pipelines/CircuitSeq.nf) which is a name change. I've also removed the 'sanger' column from the sample sheet, as we have a separate pathway to compare those results. 

I'm testing the methylation steps now, though that takes some time. Let me know how it goes for you!

**Comment by EdGreen21** [comment]
hi @aaronmck are you sure about removing the sangers column from the sample sheet - still seems to be in [example_sample_sheet.tsv](https://github.com/mckennalab/Circuitseq/blob/main/example_sample_sheet.tsv). I'm just writing the scripts to adapt our QC to your pipeline, and wondered whether this column is still required

**Comment by aaronmck** [comment]
Hi @EdGreen21. Sorry, we still had some old example files floating around the repository. I've cleaned those up, the up-to-date example files are located here: https://github.com/mckennalab/Circuitseq/tree/main/pipelines/examples
