### ISSUE TITLE
option to run straight from fastq

### ISSUE THREAD

**Issue by osilander** [mckennalab/Circuitseq#5]
Would be great to have an option to run without basecalling. Or maybe that's in the config file already?

**Comment by aaronmck** [comment]
We do have something in the pipeline for this. if you add the following parameters to your nextflow.config file:

`
params.basecalling_dir = "/directory_for_basecalled_data/pass/"
params.base_calling_summary_file = "/directory_for_basecalled_data/sequencing_summary.txt"
`

Replacing the directory_for_basecalled_data with your path. This is a little experimental so let us know if you run into issues.

**Comment by osilander** [comment]
Sweet I’ll take a look

**Comment by femiliani** [comment]
you also have to include 
`params.use_existing_basecalls = true`
to your nextflow.config
