### ISSUE TITLE
error in finding mismatch matrix file

### ISSUE THREAD

**Issue by osilander** [mckennalab/Circuitseq#6]
Hi,
I went ahead and used unbasecalled data for simplicity. It completes the basecalling, but I now have an error when it looks for the mismatch file (below,  /fullPathToMyCircuitseq/barcodes/v2 is a placeholder for the actual very long path)
```
Command error:
  INFO:    Converting SIF file to temporary sandbox...
  WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (530) bind mounts
  Error: Could not find mismatch matrix file "/fullPathToMyCircuitseq/barcodes/v2", check configuration.
  INFO:    Cleaning up image...
```

The .command.sh log file says:
```
#!/bin/bash -ue
guppy_barcoder \
    --input_path pass \
    --save_path saved_data \
    --data_path /fullPathToMyCircuitseq/barcodes/v2 \
    --barcode_kits MY-CUSTOM-BARCODES \
    --front_window_size 120 \
    --min_score_mask 30 \
    -x cuda:all \
    --min_score 65 \
    -q 1000000 \
    --compress_fastq
chmod -R o+rw ./
```

When I look inside `/fullPathToMyCircuitseq/barcodes/v2` I find several files including a config file and a mismatch file that it looks like the config file specifies, `5x5_mismatch_matrix.txt`

I then put the actual name of the mismatch file into the bash script I'm using so that it has 
```
--barcodes /fullPathToMyCircuitseq/barcodes/v2/5x5_mismatch_matrix.txt
```
But this gives the same error.

I then went to the nextflow script and changed the MY-CUSTOM-BARCODES to SQK-RBK004 but got the same error but of course the .command.sh file now says:
```
#!/bin/bash -ue
guppy_barcoder \
    --input_path pass \
    --save_path saved_data \
    --data_path  /fullPathToMyCircuitseq/barcodes/v2 \
    --barcode_kits SQK-RBK004 \
    --front_window_size 120 \
    --min_score_mask 30 \
    -x cuda:all \
    --min_score 65 \
    -q 1000000 \
    --compress_fastq
chmod -R o+rw ./
```

Do you know what I'm doing wrong?

**Comment by aaronmck** [comment]
Sorry this is a bit unclear (I'll make an issue to fix this)... are you using our barcode combinations or are you using your own? If you're using our V2 (or V1) the path is actually internal to the Docker container and can stay

```/plasmidseq/barcodes/v2/ ```

or V1. If you're using your own barcodes the path change you have should work, though I see if I can debug it with our own barcode files moved outside the container. Also worth noting we're still running Guppy V5.x in the pipeline, which has slightly different barcode files than in version 6.X.

**Comment by osilander** [comment]
Sorry for the confusion. I now have a new error with the changed barcode path above (`/plasmidseq/barcodes/v2/`):

```
Error executing process > 'GuppyDemultiplex'

Caused by:
  Missing output file(s) `saved_data/barcode**/**.fastq.gz` expected by process `GuppyDemultiplex`

Command executed:

  guppy_barcoder \
      --input_path pass \
      --save_path saved_data \
      --data_path /plasmidseq/barcodes/v2 \
      --barcode_kits MY-CUSTOM-BARCODES \
      --front_window_size 120 \
      --min_score_mask 30 \
      -x cuda:all \
      --min_score 65 \
```

I'm just using RBK004 barcodes 1-6. I put those in the config file just as those numbers 1-6, as I thought the "position" is the barcode number. However, the sample tsv has no "position" 85 and instead has a "position" 97, so maybe this is incorrect.  I also think the header in the docs and in the sample files are different. Docs say: Position, SampleID, Reference. Sample config file says:  position, sample, reference.

Regardless, my tsv file is:
```
position        sample  reference
1       pcas_1  NA
2       pcas_2  NA
3       pcas_3  NA
4       pcas_4  NA
5       pcas_5  NA
6       pcas_6  NA
```
where the plasmid names are just pcas_N, etc.

I'm confused what you mean by _are you using our barcode combinations or are you using your own?_

Thanks for all the help.

Cheers.

**Comment by aaronmck** [comment]
Hi Olin,

Sorry for the delay here, and thanks for catching the column headers issue, I've changed the sample headers on the main page. We haven't built-in support for other barcoding options besides our own, but I'll put in a github issue to add this. To test if this would work for you, you could change the ` guppy_barcoder` task to look _something_ like: 

`
guppy_barcoder \\
        --input_path ${basecalled} \\
        --save_path saved_data \\
        --barcode_kits RBK004 \\
        --front_window_size 120 \\
        --min_score_mask 30 \\
        -x $params.gpu_slot \\
        --min_score $params.barcode_min_score \\
        -q 1000000 \\
        --compress_fastq
    chmod -R o+rw ./
`
Changing the `--barcode_kits` parameter and removing the `--data_path` parameter. I'll see if we can test this out on our end too.
