### ISSUE TITLE
Can I use other barcoding method than LSK?

### ISSUE THREAD

**Issue by dmsalsgh97** [mckennalab/Circuitseq#8]
Hi, thanks for developing the pipeline.

I successfully assembled your sample dataset, and Now I want to apply it to my sample. (barcoded by SQK-RBK110.96)
Unfortunately, barcode multiplexing in the circuitseq pipeline only knows LBK version of barcodes, and it makes failed demultiplexing...

I already demultiplexed my sample with valid RBK barcodes, and I have demultiplexed fastq files.
So, Can I skip the guppy_demultiplex step and start from porechop step?

I tried to find the related option, but the only option was skipping guppy basecalling step.

thanks.

**Comment by aaronmck** [comment]
Hi @dmsalsgh97,

Sorry for the delay here. It might be easier to support demultiplexing with the Nanopore 96x rapid barcoding kit, which I bet others will use too and it would avoid turning the pipeline into a swiss army knife. If you're still interested in testing this I'll add the option within the ~ next day and you can try out the new version. Let me know if this makes sense,

Aaron

**Comment by dmsalsgh97** [comment]
Hi Aaron,
Thanks for reply!

Yeah, many people using RBK for plasmid nanopore sequencing too. 

Another option could be an option for skip the guppy_demultiplex step and get input fasta demultiplexed by users.

Thanks,
Minho

**Comment by femiliani** [comment]
Hey Minho, 

Sorry for the delay but I finally got it up and running. I included the nanopore barcode info (as of guppy5.0.16, I am waiting to update everything when dorado becomes the official basecaller). 

I made some additional changes to the pipeline and docker image so you will have to clone the new directory and get the new singularity file (all in the readme). I cleaned up the pipeline so that all the parameters are set in the run_nf.sh file which should simplify it for everyone. All of the info is in the readme. In your case you will be able to use your barcodes by setting:
--barcode_kit "SQK-RBK110-96"
--barcodes /plasmidseq/barcodes/nanopore_official

Hopefully this works, I've been limited in testing it out because we dont have any data with the nanopore barcoding kits. 

Let me know if it works!

**Comment by dmsalsgh97** [comment]
Hi femiliani,
thanks for updating your pipeline!

Now, I want to try my RBK barcoded sample on the new version and share the results, but there is a problem...

Following the new instruction, I newly made *.sif file and changed the run_nf.sh script accordingly.
But when I run the script, It makes a weird error about parameter --fast5...

below is my run_nf.sh script

```
NXF_VER=21.10.6 nextflow run /node210data/minho2/Circuitseq/pipelines/CircuitSeq.nf \
           --GPU ON \
           -c /node210data/minho2/Circuitseq/pipelines/nextflow.config \
           -with-singularity /node210data/minho2/plasmidassembly.sif \
           --samplesheet /node210data/minho2/circuit_seq_out/pTol2-ubi-dsRed/samplesheet.tsv \
           --use_existing_basecalls true \
           --fast5 "" \
           --basecalling_dir /node210data/minho2/circuit_seq_out/pTol2-ubi-dsRed \
           --base_calling_summary_file /node210data/minho2/circuit_seq_out/pTol2-ubi-dsRed/sequencing_summary.txt \
           --barcodes /plasmidseq/barcodes/nanopore_official/ \
           --barcode_kit "SQK-RBK110-96" \
           --guppy_model dna_r9.4.1_450bps_sup.cfg \
           --medaka_model r941_min_sup_g507 \
           --gpu_slot cuda:0 \
           --barcode_min_score 45 \
           --quality_control_processes true \
           -resume
```

And it is the warning and error messages
```
Launching `/node210data/minho2/Circuitseq/pipelines/CircuitSeq.nf` [confident_ritchie] - revision: 373fcf15ff
WARN: Access to undefined parameter `fast5` -- Initialise it to a default value eg. `params.fast5 = some_value`
Missing `fromPath` parameter
run_nf.sh: line 3: --GPU: command not found
run_nf.sh: line 4: -c: command not found
run_nf.sh: line 5: -with-singularity: command not found
run_nf.sh: line 6: --samplesheet: command not found
run_nf.sh: line 7: --use_existing_basecalls: command not found
run_nf.sh: line 8: --fast5: command not found
run_nf.sh: line 9: --basecalling_dir: command not found
run_nf.sh: line 10: --base_calling_summary_file: command not found
run_nf.sh: line 11: --barcodes: command not found
run_nf.sh: line 12: --barcode_kit: command not found
run_nf.sh: line 13: --guppy_model: command not found
run_nf.sh: line 14: --medaka_model: command not found
run_nf.sh: line 15: --gpu_slot: command not found
run_nf.sh: line 16: --barcode_min_score: command not found
run_nf.sh: line 17: --quality_control_processes: command not found
run_nf.sh: line 18: $'-resume\r': command not found
run_nf.sh: line 19: $'\r': command not found
run_nf.sh: line 20: $'\r': command not found
(base) [minho2@node210 pTol2-ubi-dsRed]$ 
```

Thanks,
Minho

**Comment by femiliani** [comment]
Sorry about that, very curious. I just tried redownloading the sif and cloning the repo and it works for me starting from fastq. It's weird that it is not accepting fast5 as a parameter.

Can you try setting `--fast5 "none"` instead of "" I noticed i made a mistake in the read me and suggested using "" for it.

**Comment by dmsalsgh97** [comment]
Oh, I see.

When I changed the run script --fast5 "none", the pipeline is working correctly!
Thanks for the quick reply!

I'm looking for your new-version guppy_demultiplex step, and it works correctly.
![image](https://user-images.githubusercontent.com/42495757/179144350-007a3690-0c99-463a-871b-da2ff6b0f56f.png)

All my reads barcoded as #40, and it is working correctly!

Thanks,
Minho

**Comment by femiliani** [comment]
Glad that fixed it! Also, i had never looked at the RBK barcodes, those are massive. So you might want to keep the minimum score at the standard 60-65 

Hope the rest of the pipeline runs smoothly. I'll keep this issue open for now.

**Comment by dmsalsgh97** [comment]
Hi Francesco,
I think the pipeline worked everything correctly.

Our team tried to clone 9.1kb of vector, but gel size estimation showed huge deletion of 3kb length...
We are looking for the origin of this 3kb length deletion, and it was still mysterious (until today)...

Surprisingly, Circuit-seq successfully denovo assembled it and find out the problem!
Circuit-seq assembly output is 6.1kb in length, and it is pointing out the deleted 3kb region. wow!

(Circuit-seq output, annotated by pLannotate.)
![image](https://user-images.githubusercontent.com/42495757/179148021-4864e673-43ba-488e-bdc9-aa22be5478ba.png)

Thanks again for developing this pipeline. In my think, Circuit-seq will be a huge help for troubleshooting!

As a tiny suggestion, there is a plasmid annotating tool "pLannotate". (https://github.com/barricklab/pLannotate)
Integrating pLannotate into your pipeline could be very meaningful improvement!

I'll close this issue.

Sincerely,
Minho

**Comment by femiliani** [comment]
Hello Minho, 
Really glad to hear it all worked out and that you found CircuitSeq useful! 

I am trying to get pLannotate integrated into our pipeline, running into some issues. But for now I have a quick and dirty fix up here: https://github.com/mckennalab/Circuitseq/blob/main/plannotate/ should at least make it easy to annotate a whole batch of assemblies while I sort out why singularity feels the need to give me another headache. 

-Francesco
